install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-ARM64.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
before:
  - rm -rf public
script:
  - hugo
branches:
  only:
    - master
