baseurl = "https://hugo.wiredstudios.net/"
languageCode = "en-us"
title = "Wired Studios"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "Marin Joe Garcia"
    site_description = "A new kind of interactive design and development company."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/wiredstudios-logo.png"
    header_background = "img/iStock1056212578.jpg"
    header_title = "A new kind of interactive design and development company."
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "wiredstudiosinc"
    facebook  = "wiredstudios"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "wiredstudios"
    gplus     = ""
